# Generated by Django 3.2.5 on 2021-07-18 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='big_score',
            field=models.IntegerField(default=0, verbose_name='대변점수'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gas_score',
            field=models.IntegerField(default=0, verbose_name='방귀점수'),
        ),
        migrations.AlterField(
            model_name='user',
            name='small_score',
            field=models.IntegerField(default=0, verbose_name='소변점수'),
        ),
        migrations.AlterField(
            model_name='user',
            name='total_score',
            field=models.IntegerField(default=0, verbose_name='총합'),
        ),
    ]
