# Generated by Django 3.2.5 on 2021-07-18 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='choice',
            field=models.CharField(choices=[('2', '소변'), ('3', '방귀'), ('1', '대변')], max_length=80, null=True),
        ),
    ]
