# Generated by Django 3.2.5 on 2021-07-20 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_alter_board_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='choice',
            field=models.CharField(choices=[('3', '방귀'), ('2', '소변'), ('1', '대변')], max_length=80, null=True),
        ),
    ]
