# Generated by Django 3.2.5 on 2021-07-27 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0010_alter_board_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='body',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='choice',
            field=models.CharField(choices=[('3', '방귀'), ('1', '대변'), ('2', '소변')], max_length=80, null=True),
        ),
    ]
