# Generated by Django 3.2.5 on 2021-07-27 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0011_auto_20210727_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='choice',
            field=models.CharField(choices=[('2', '소변'), ('1', '대변'), ('3', '방귀')], max_length=80, null=True),
        ),
    ]
